#!/bin/bash
#
#  Filename:  ~/.ssh/config 
#  Style Guide Reference: https://google.github.io/styleguide/shell.xml#File_Header
#  Summary: Default User ssh client configuration settings
#
# - Host Settings used by ssh client for all connections.
#
# - For additional details on the purpose of each directive below in configuring the ssh
#   client behavior visit https://www.openssh.com/manual.html or run the following command:
#
#   $ man ssh
#
# - The defaults can be overridden in specific host directives further down to accomodate for
#   sshd daemon conifgurations and defaults used by less common host operating systems.  Normally,
#   this is not often needed, but for an example see the ControlPath directive defaults and the
#   override needed to enable ssh client access without generating weird errors in OpenShift v1.
#
#  - Online References
#    - Speed Up ssh by reusing connections : https://puppet.com/blog/speed-up-ssh-by-reusing-connections
#    - difficulties with ssh-agent in macOS Sierra : 
#	https://www.reddit.com/r/osx/comments/52zn5r/difficulties_with_sshagent_in_macos_sierra/
#    -  macOS Sierra 10.12 SSH Keys : https://testequals.com/2016/09/09/macos-sierra-10-12-ssh-keys/
#    - Saving SSH keys in macOS Sierra keychain : https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain

Host github.com
  PreferredAuthentications publickey
  HostName github.com
  IdentityFile ~/.ssh/github.com/id_rsa
  VerifyHostKeyDNS yes
  StrictHostKeyChecking yes
  PasswordAuthentication no

Host bitbucket.org
  PreferredAuthentications publickey
  HostName bitbucket.com
  IdentityFile ~/.ssh/bitbucket.com/id_rsa
  VerifyHostKeyDNS yes
  StrictHostKeyChecking yes
  PasswordAuthentication no

Host *.rhcloud.com
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/test-beejhuff.rhcloud.com/id_rsa
  IdentitiesOnly yes
  VerifyHostKeyDNS yes
  StrictHostKeyChecking no
  PasswordAuthentication no
  User 574138a70c1e66236c000033
  ControlPath /tmp/%r@%h:%p

Host erx-1
  #PreferredAuthentications publickey
  Hostname 192.168.1.1
  #IdentityFile ~/.ssh/erx-1/id_ed25519
  User beejhuff
  #IdentitiesOnly yes
  #VerifyHostKeyDNS yes
  #StrictHostKeyChecking no
  #PasswordAuthentication no

Host erx-2
  Hostname 192.168.0.1
  User admin
  Port 2222

Host git.sitebiz.com
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/git.sitebiz.com/id_rsa

Host tombstonetactical-dev.sitebiz.com
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/git.sitebiz.com/id_rsa

Host *
  ServerAliveCountMax 10
  ServerAliveInterval 30
  Compression yes
  ControlMaster auto
  ControlPath ~/.ssh/sockets/master-%l-%r@%h:%p
  ControlPersist 600

  # NOTE: The following directive is only valid in macOS Sierra 10.12.1 or higher
  #UseKeychain yes

