#!/bin/bash
#
#  Filename:  ~/.ssh/config 
#  Style Guide Reference: https://google.github.io/styleguide/shell.xml#File_Header
#  Summary: Default User ssh client configuration settings
#
# - Host Settings used by ssh client for all connections.
#
# - For additional details on the purpose of each directive below in configuring the ssh
#   client behavior visit https://www.openssh.com/manual.html or run the following command:
#
#   $ man ssh
#
# - The defaults can be overridden in specific host directives further down to accomodate for
#   sshd daemon conifgurations and defaults used by less common host operating systems.  Normally,
#   this is not often needed, but for an example see the ControlPath directive defaults and the
#   override needed to enable ssh client access without generating weird errors in OpenShift v1.
#
#  - Online References
#    - Speed Up ssh by reusing connections : https://puppet.com/blog/speed-up-ssh-by-reusing-connections
#    - difficulties with ssh-agent in macOS Sierra : 
#	https://www.reddit.com/r/osx/comments/52zn5r/difficulties_with_sshagent_in_macos_sierra/
#    -  macOS Sierra 10.12 SSH Keys : https://testequals.com/2016/09/09/macos-sierra-10-12-ssh-keys/
#    - Saving SSH keys in macOS Sierra keychain : https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain

# TODO: Test all hosts below as I seem to recall there might have been a specific reason I moved the 
# default directive the bottom of the file when I originally wrote it, though I can't remember exactly
# what that was at the moment...though I seem to recall it may have had something to do with the wildcard
# that I had to use to handle key-based logins for the range of RedHat FQDNs we might need to login to
# when using OpenShift....haven't used it in a while so may need to validate if this is even necessary....

#-- Default ssh Configuration used to connect to all Hosts --#

Host *
  ServerAliveCountMax 10
  ServerAliveInterval 30
  Compression yes
  ControlMaster auto
  ControlPath ~/.ssh/sockets/master-%l-%r@%h:%p
  ControlPersist 600
  CompressionLevel 7
  AddKeysToAgent yes

# The following directive is only valid in macOS Sierra 10.12.1 or higher
#
#  UseKeychain yes

#-- End Default ssh Configuration used to connect to all Hosts --#

#-- RedHat OpenShift SSH Configuration Defaults --#

Host *.rhcloud.com 
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/test-beejhuff.rhcloud.com/id_rsa
  IdentitiesOnly yes
  VerifyHostKeyDNS yes
  StrictHostKeyChecking no
  PasswordAuthentication no  
  User 574138a70c1e66236c000033
  ControlPath /tmp/%r@%h:%p

#-- End RedHat OpenShift SSH Configuration --#

#-- GitHub ssh Configuration Defaults --#

Host github.com
  PreferredAuthentications publickey
  HostName github.com
  IdentityFile ~/.ssh/github.com/id_rsa

#-- End GitHub ssh Configuration. --#

#-- BitBucket  ssh Configuration Defaults --#

Host bitbucket.com
  PreferredAuthentications publickey
  HostName bitbucket.com
  IdentityFile ~/.ssh/bitbucket.com/id_rsa

#-- End BitBucket ssh Configuration. --#
